### ISSUE TITLE
"Traceback (most recent call last):" error.

### ISSUE THREAD

**Issue by mk0lev** [willHol/polybar-crypto#1]
Hello, I experience the following error, while running polybar-crypto with default config: I get this `Traceback (most recent call last):` printed in the polybar, where the cryptocurrencies are usually meant to be. I'm not good with python, but I tried googling it and I haven't had success with it. So any suggestions?

**Comment by mk0lev** [comment]
I had ~/.config/polybar/crypto-config in the python script, but it should be /home/martin/.config/polybar/crypto-config. Now it works.

**Comment by IcyKit** [comment]
Same here. Editing of path doesn't work

**Comment by thien0709** [comment]
> Same here. Editing of path doesn't work

me too , it doesn't work
