### ISSUE TITLE
cryptocoins Font

### ISSUE THREAD

**Issue by mk0lev** [willHol/polybar-crypto#2]
Hello, 

can you give some advice how to get the cryptocoins font running with polybar-crypto. I downloaded the package and added the font to the polybar config file, but I don't know how or from where to copy/paste the icons in the crypto-config file. 

Thanks, Martin

**Comment by rishadfb** [comment]
I got it working by installing cryptocoins via npm (globally): `npm install -g cryptocoins`. If you get any "permission denied" errors, you may have to try `sudo npm install -g cryptocoins`.

**Comment by mk0lev** [comment]
Thanks I did install it this way, but where do you copy the icons from? Is there a cheatsheet or anything?
Thanks

**Comment by rishadfb** [comment]
I use Manjaro so I installed `gucharmap` from the Arch repos. 

Here are some steps that might be useful:

1. Open `gucharmap` and choose the "cryptocoins" font in the dropdown. 
2. Under the left column named "Unicode Block", choose Private Use Area. 
3. On the right, you should see all the icons. If not, scroll up or down till you see them. Double click on the one you want. 
4. At the bottom you will see a box called "Text to copy:" with the icon you want in it. You can copy the icon from there.

**Comment by mk0lev** [comment]
Thanks for the answer! I installed it and I see most of the icons, but none of the cryptocoins icons, I see them like this "". I probably messed up something with the fonts, but I don't really know what. I configured cryptocoins font in the polybar config and that was it. Any suggestions?

**Comment by rishadfb** [comment]
Where do you see most of the icons?

**Comment by mk0lev** [comment]
If you look at the Hex number of the icons, I don't see them from U+E2AC to U+E5F4 and then from U+E828 to U+EFC0 and then from U+F4AC until the end. The Hex numbers you can find down left.

**Comment by fwanky** [comment]
> If you look at the Hex number of the icons, I don't see them from U+E2AC to U+E5F4 (a little bit after the beginning) and then from U+E828 to U+EFC0 (mid) and then from U+F4AC until the end. The Hex numbers you can find down left when you select an icon.
> 
> EDIT: I just noticed I don't have a cryptocoins font to choose. I've missed that step, sorry. I installed it via npm. What's wrong?

I'm having the same issue. it just doesn't seem to install using NPM, any ideas?

**Comment by SplendidX** [comment]
I've been having a lot of issues with this as-well, plus I figured finding every icon just to display an additional currency nicely isn't great, so I made an alternative to this script which largely works the same, minus configuration files and icon hunting. The font I use is also modern and is included.

[SplendidX/polybar-cryptocurrency](https://github.com/SplendidX/polybar-cryptocurrency)
