### ISSUE TITLE
API is no longer available

### ISSUE THREAD

**Issue by rholak** [willHol/polybar-crypto#8]
When trying to access the API, the following error occurs:

`{"statusCode": 410,"error": "Gone","message": "WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)"}`

The new API mentioned does offer a free tier that requires an API key - this could be configured in `crypto-config`.

**Comment by Emobe** [comment]
something tells me this isn't maintained anymore
